#!/bin/bash
# Run PyFlakes and PEP8 tests.
# Just write ./runtest in terminal to test program

echo "      PYFLAKES TESTS:"
echo "common.py"
pyflakes common.py
echo "source.py"
pyflakes source.py
echo "catalogue.py"
pyflakes catalogue.py

echo "      PYCODESTYLE (PEP8) TESTS:"
echo "common.py"
pycodestyle common.py
echo "source.py"
pycodestyle source.py
echo "catalogue.py"
pycodestyle catalogue.py
