#!/bin/bash

echo "  PYFLAKES TESTS:"
echo "common.py"
pyflakes common.py
echo "source.py"
pyflakes source.py
echo "catalogue.py"
pyflakes catalogue.py
echo "  PEP8 TESTS:"
echo "common.py"
pep8 common.py
echo "source.py"
pep8 source.py
echo "catalogue.py"
pep8 catalogue.py
